url=https://www.saucedemo.com/
username=standard_user
password=secret_sauce
productPageTitle=Products
sortingOptions=Name (A to Z), Name (Z to A), Price (low to high), Price (high to low)
product1=Sauce Labs Backpack
product2=Sauce Labs Bike Light  
product1Description=carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.
product2Description=A red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.
product1Prize=$29.99
product2ProductPrice=$9.99
inValidusername=locked_out_user
errorMsg=Epic sadface: Sorry, this user has been locked out.
firstName=John
lastName=Doe
fnameErrorMsg=Error: First Name is required
lnameErrorMsg=Error: Last Name is required
postalCodeErrorMsg=Error: Postal Code is required
zipCode=12345 
checkoutOverviewTitle=Checkout: Overview
checkoutCompleteTitle=Checkout: Complete!   

